routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', array('as'=> 'front.home', 'uses' => 'FrontController@index'));

// contact route
Route::post('/contact', array('as'=> 'front.contact', 'uses' => 'FrontController@contact'));
Route::get('product/{slug}', array('as'=> 'front.product', 'uses' => 'FrontController@productIndex'));

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

Route::group(['prefix' => 'admin'], function () {

	Route::resource('sliders', 'Admin\SliderController');
	Route::resource('products', 'Admin\ProductController');
	Route::resource('contacts', 'Admin\ContactController');
	Route::resource('settings', 'Admin\SettingController');

	Route::post('productImage/store', array('as'=> 'productsImages.store', 'uses' => 'Admin\ProductImgController@store'));
	Route::get('productImage/create/{id}', array('as'=> 'productsImages.create', 'uses' => 'Admin\ProductImgController@create'));
	Route::get('productImage/{id}', array('as'=> 'productsImages.index', 'uses' => 'Admin\ProductImgController@index'));
	Route::delete('productImage/delete/{id}', array('as'=> 'productsImages.destroy', 'uses' => 'Admin\ProductImgController@destroy'));

});

app/Contact.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Config;

class Contact extends Model
{
    protected $fillable = ['name','email_id','mobile_no','message'];

    public function createData($input)
    {
    	return static::create(array_only($input,$this->fillable));
    }

    public function getData($input)
    {
    	$data = static::select("contacts.*");

        if (!empty($input['filter']) && is_array($input['filter'])) {
        
            foreach ($input['filter'] as $column => $row) {
                if (!empty($column) && !empty($row["value"]) && is_array($row)) {
                    $operator = Config::get("setting.type", 1)[$row["type"]];

                    if ($row["type"] == 7) {
                        $data->where("Contacts.".$column, $operator, "%{$row["value"]}%");
                    } else {
                        $data->where("Contacts.".$column, $operator, $row["value"]);
                    }
                }
            }
        }

        return $data = $data->latest()->paginate(10);
    }
    
    public function destroyData($id)
    {
        return static::find($id)->delete();
    }

    public function getTotalContact()
    {
        return static::count();
    }
}

app/Http/Controllers/Admin/ContactController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Controllers\AdminController;
use App\Contact;

class ContactController extends AdminController
{
	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function __construct()
	{
		parent::__construct();
		$this->contact = new Contact;
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function create()
	{	
		return view('Admin.Contact.create');
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function index(Request $request)
	{
		$contact = $this->contact->getData($request->all());
		return view('Admin.Contact.index',compact('contact'));
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function store(Request $request)
	{	

	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function destroy($id)
    {
        $this->contact->destroyData($id);
        notificationMsg('danger',$this->crudMessage('delete','Contact'));
        return redirect()->route('contacts.index');
    }

}

resources/views/Admin/Contact/index.blade.php
@extends('adminTheme.default')

@section('title')
Manage Contact
@endsection

@section('content')
<section class="content-header">
  <h1>
    <i class="fa fa-phone" aria-hidden="true"></i> Manage Contact
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Contact</li>
  </ol>
</section>
<section class="content">
<div class="row">
    <div class="col-lg-12">
        <div class="pull-left">
            <h1 class="page-header">
            </h1>
        </div>
        <div class="pull-right">
        	<!-- <a href=""><button class="btn btn-success"><i aria-hidden="true" class="fa fa-plus"></i> Create New Product</button></a> -->

            <button class="btn btn-primary search-modules btn-flat" data-toggle="tooltip" title="Search !"><i class="fa fa-search"></i></button>

        </div>
    </div>
</div><br>
@include('Admin.Contact.search')
<div class="box box-info">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <h3 class="box-title">Contact List</h3>
    </div>
    <div class="box-body">
    <table class="table table-bordered">
    <thead>
        <tr>
            <th width="50px">No</th>
            <th>Name</th>
            <th>Email</th>
            <th>Mobile No.</th>
            <th>Message</th>
            <th width="220px">Action</th>
        </tr>
    </thead>
    <tbody>
    @if(!empty($contact) && $contact->count())
        @foreach($contact as $key => $value)
        <tr>
            <td>{{ ++$key }}</td>
            <td>{{ $value->name }}</td>
            <td>{{ $value->email_id }}</td>
            <td>{{ $value->mobile_no }}</td>
            <td>{{ $value->message }}</td>
            <td>
                <button class="btn btn-danger btn-sm btn-flat remove-crud" data-id="{{ $value->id }}" data-toggle="tooltip" data-placement="top" title="Delete" data-action="{{ route('contacts.destroy',$value->id) }}"><i class="fa fa-trash" aria-hidden="true"></i></button>
            </td>
        </tr>
        @endforeach
    @else
        <td colspan="6" class="text-center">There are no contact.</td>
    @endif
    </tbody>
</table>
</div>
<div class="text-center">
    @if(!empty($contact) && $contact->count())
    {!! $contact->appends(Input::all())->render() !!}
    @endif
</div>
</section>
@endsection
@section('script')
<script type="text/javascript">
    jQuery(".search-modules").click(function(e) {
        
        e.preventDefault();
        jQuery(".filter-panel").toggle("slow");

    });
</script>
@endsection

resources/views/Admin/Contact/search.blade.php
<div class="box box-success filter-panel {{Input::get("filter",false)?'filter-in':'filter-out'}}">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <h3 class="box-title">Searching</h3>
    </div>
    <div class="box-body">

        {!! Form::open(array('method'=>'get','class'=>'form-filter form-inline')) !!}
        <ul class="search">
            <li>
                <div class='form-group'>
                    {!! Form::label('filter[name][value]', 'Name',array('class'=>'control-label')) !!}
                    {!! Form::text('filter[name][value]',Input::get("filter.name.value"),array('class'=>'form-control','placeholder'=>'Enter Name')) !!}{!! Form::hidden('filter[name][type]','7') !!}
                </div>
            </li>
            <li>
                <div class='form-group'>
                    {!! Form::label('filter[email_id][value]', 'Email',array('class'=>'control-label')) !!}
                    {!! Form::text('filter[email_id][value]',Input::get("filter.email_id.value"),array('class'=>'form-control','placeholder'=>'Enter Email')) !!}{!! Form::hidden('filter[email_id][type]','7') !!}
                </div>
            </li>
            <li>
                <div class='form-group'>
                    <br/>
                    <button class="btn btn-success btn-flat">Submit</button>
                </div>
            </li>
        </ul>
        {!! Form::close() !!}
    </div>
</div>