routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', array('as'=> 'front.home', 'uses' => 'FrontController@index'));

// contact route
Route::post('/contact', array('as'=> 'front.contact', 'uses' => 'FrontController@contact'));
Route::get('product/{slug}', array('as'=> 'front.product', 'uses' => 'FrontController@productIndex'));

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

Route::group(['prefix' => 'admin'], function () {

	Route::resource('sliders', 'Admin\SliderController');
	Route::resource('products', 'Admin\ProductController');
	Route::resource('contacts', 'Admin\ContactController');
	Route::resource('settings', 'Admin\SettingController');

	Route::post('productImage/store', array('as'=> 'productsImages.store', 'uses' => 'Admin\ProductImgController@store'));
	Route::get('productImage/create/{id}', array('as'=> 'productsImages.create', 'uses' => 'Admin\ProductImgController@create'));
	Route::get('productImage/{id}', array('as'=> 'productsImages.index', 'uses' => 'Admin\ProductImgController@index'));
	Route::delete('productImage/delete/{id}', array('as'=> 'productsImages.destroy', 'uses' => 'Admin\ProductImgController@destroy'));

});

app/Slider.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{

    protected $fillable = ['image'];

    public function createData($input)
    {
    	return static::create(array_only($input,$this->fillable));
    }

    public function getData($input)
    {
    	$data = static::select("sliders.*");
        return $data = $data->latest()->paginate(10);
    }
    
    public function destroyData($id)
    {
        return static::find($id)->delete();
    }

    public function findData($id)
    {
        return static::find($id);
    }

    public function getTotalSlider()
    {
        return static::count();
    }

    public function fgetSlider()
    {
        return static::get();
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Controller;
use App\Slider;
use Validator;
use App\ImageUpload;

class SliderController extends AdminController
{	
	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function __construct()
	{
		parent::__construct();
		$this->slider = new Slider;
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function create()
	{	
		return view('Admin.Slider.create');
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function index(Request $request)
	{
		$slider = $this->slider->getData($request->all());
		return view('Admin.Slider.index',compact('slider'));
	}

	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function store(Request $request)
	{	
		$this->validate($request,[
            'image' => 'required|image',
        ]);

		$input = $request->all();

        if($request->hasfile('image')){
        	$input['image'] = ImageUpload::upload('/upload/slider',$request->file('image'));
        }

		 $this->slider->createData($input);
         notificationMsg('success',$this->crudMessage('add','slider'));
         return redirect()->route('sliders.index');
	}
	
	/**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function destroy($id)
    {
        $this->slider->destroyData($id);
        notificationMsg('success',$this->crudMessage('delete','slider'));
        return redirect()->route('sliders.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function show($id)
    {   
        $slider = $this->slider->findData($id);
        return view('Admin.Slider.view',compact('slider')); 
    }
}

resources/views/Admin/Slider/create.blade.php
@extends('adminTheme.default')

@section('title')
Create Slider
@endsection

@section('content')
<section class="content-header">
  <h1>
    Create Slider
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('sliders.index') }}">Slider</a></li>
    <li class="active">Create New Slider</li>
  </ol>
</section>
<section class="content">
<a href="{{ route('sliders.index') }}" class="btn btn-primary btn-flat pull-right" data-toggle="tooltip" title="Back !"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><br><br>
<div class="box box-primary">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="fa fa-sliders" aria-hidden="true"></i>
        <h3 class="box-title">Slider</h3>
    </div>

    @if($errors->count() > 0)
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                @foreach($errors->all() as $er )
                    <ul>
                        <li>{{ $er }}</li>
                    </ul> 
                @endforeach
        </div>
    @endif

    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="modal-body">
                    {!! Form::open(array('route'=>'sliders.store','method'=>'POST','files'=>'true')) !!}
                        <div class="form-group">
                            <label>Image:</label>
                            {!! Form::file('image',['class'=>'form-control']) !!}
                        </div>
                        <div class="box-footer clearfix no-border">
                            <a href="{{ route('sliders.index') }}" class="btn btn-danger btn-flat pull-right" style="margin-left: 10px;" data-toggle="tooltip" title="Cancel !"><i class="fa fa-times" aria-hidden="true"></i></a>
                            <button type="submit" class="btn btn-success pull-right btn-flat" data-toggle="tooltip" title="Submit !"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/Admin/Slider/index.blade.php
@extends('adminTheme.default')

@section('title')
Manage Slider
@endsection

@section('content')
<section class="content-header">
  <h1>
    <i class="fa fa-sliders" aria-hidden="true"></i> Manage Slider
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Slider</li>
  </ol>
</section>
<section class="content">
<div class="row">
    <div class="col-lg-12">
        <div class="pull-left">
            <h1 class="page-header">
            </h1>
        </div>
        <div class="pull-right">
        	<a href="{{ route('sliders.create') }}"><button class="btn btn-success btn-flat" data-toggle="tooltip" title="Create New Slider !"><i aria-hidden="true" class="fa fa-plus"></i></button></a>
        </div>
    </div>
</div><br>
<div class="box box-info">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <h3 class="box-title">Slider List</h3>
    </div>
    <div class="box-body">
    <table class="table table-bordered">
    <thead>
        <tr>
            <th width="50px">No</th>
            <th>image</th>
            <th width="220px">Action</th>
        </tr>
    </thead>
    <tbody>
    @if(!empty($slider) && $slider->count())
        @foreach($slider as $key => $value)
        <tr>
            <td>{{ ++$key }}</td>
            <td><img src="/upload/slider/{{ $value->image }}" style="width:100px;height:100px;"></td>
            <td>
                @include('Admin.Slider.view')
                <a href="{{ route('sliders.show',$value->id) }}" class="btn btn-sm btn-info btn-flat" data-toggle="modal" data-target="#myModal-{{ $value->id }}"><i aria-hidden="true" class="fa fa-eye" data-toggle="tooltip" title="View !"></i></a>
                <button class="btn btn-danger btn-sm btn-flat remove-crud" data-id="{{ $value->id }}" data-toggle="tooltip" data-placement="top" title="Delete" data-action="{{ route('sliders.destroy',$value->id) }}"><i class="fa fa-trash" aria-hidden="true"></i></button>
            </td>
        </tr>
        @endforeach
    @endif
</div>
    </tbody>
</table>
<div class="text-center">
    @if(!empty($slider) && $slider->count())
    {!! $slider->appends(Input::all())->render() !!}
    @endif
</div>
</div>
</section>
@endsection

resources/views/Admin/Slider/view.blade.php
<div class="modal fade" id="myModal-{{ $value->id }}" role="dialog">
    <div class="modal-dialog" style="width:80% !important;">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Slider image</h4>
        </div>
        <div class="modal-body">
            <div class="col-lg-12 text-center">
                <img src="/upload/slider/{{ $value->image }}" style="width:100%;">
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>