routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', array('as'=> 'front.home', 'uses' => 'FrontController@index'));

// contact route
Route::post('/contact', array('as'=> 'front.contact', 'uses' => 'FrontController@contact'));
Route::get('product/{slug}', array('as'=> 'front.product', 'uses' => 'FrontController@productIndex'));

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

Route::group(['prefix' => 'admin'], function () {

	Route::resource('sliders', 'Admin\SliderController');
	Route::resource('products', 'Admin\ProductController');
	Route::resource('contacts', 'Admin\ContactController');
	Route::resource('settings', 'Admin\SettingController');

	Route::post('productImage/store', array('as'=> 'productsImages.store', 'uses' => 'Admin\ProductImgController@store'));
	Route::get('productImage/create/{id}', array('as'=> 'productsImages.create', 'uses' => 'Admin\ProductImgController@create'));
	Route::get('productImage/{id}', array('as'=> 'productsImages.index', 'uses' => 'Admin\ProductImgController@index'));
	Route::delete('productImage/delete/{id}', array('as'=> 'productsImages.destroy', 'uses' => 'Admin\ProductImgController@destroy'));

});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Config;

class Product extends Model
{
   	protected $fillable = ['name','slug','description','image'];

   	public function createData($input)
    {
    	return static::create(array_only($input,$this->fillable));
    }

    public function getData($input)
    {
    	$data = static::select("products.*");

        if (!empty($input['filter']) && is_array($input['filter'])) {
        
            foreach ($input['filter'] as $column => $row) {
                if (!empty($column) && !empty($row["value"]) && is_array($row)) {
                    $operator = Config::get("setting.type", 1)[$row["type"]];

                    if ($row["type"] == 7) {
                        $data->where("products.".$column, $operator, "%{$row["value"]}%");
                    } else {
                        $data->where("products.".$column, $operator, $row["value"]);
                    }
                }
            }
        }

        return $data = $data->latest()->paginate(10);
    }

    public function findData($id)
    {
    	return static::find($id);
    }

    public function destroyData($id)
    {
        return static::find($id)->delete();
    }

    public function updateData($id,$input)
    {
    	return static::find($id)->update(array_only($input,$this->fillable));
    }

    public function getTotalProdut()
    {
        return static::count();
    }

    public function fgetProduct()
    {
        return static::get();
    }
    
    public function fgetProductRandom()
    {
        return static::orderByRaw("RAND()")->get();  
    }   

    public function fgetProductWithSlug($slug)
    {
        return static::where('slug',$slug)->first();
    }

    
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\Controller;
use App\Product;
use File;
use App\ImageUpload;

class ProductController extends AdminController
{
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function __construct()
	{
		parent::__construct();
		$this->product = new Product;
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function create()
	{	
		return view('Admin.Product.create');
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function index(Request $request)
	{

		$product = $this->product->getData($request->all());
	   	return view('Admin.Product.index',compact('product'));
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function store(Request $request)
	{	
		$this->validate($request,[
			'name' => 'required',
			'description' =>'required',
            'image' => 'required|image',
        ]);

        $input = $request->all();
        $input['slug'] = str_slug($input['name']);

        if($request->hasfile('image')){
            $input['image'] = ImageUpload::upload('/upload/product',$request->file('image'));
        }

        $this->product->createData($input);
        notificationMsg('success',$this->crudMessage('add','product'));
        return redirect()->route('products.index');
	}

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function update($id , Request $request)
    {
        $this->validate($request,[
			'name' => 'required',
			'description' =>'required',
        ]);
		
		$input = $request->all();

        if($request->has('image')){
        	if(!empty($input['image_old'])){
                    ImageUpload::removeFile('/upload/product/'.$input['image_old']);
            }

            $input['image'] = ImageUpload::upload('/upload/product',$request->file('image'));	
        }

		$this->product->updateData($id,$input);
        notificationMsg('success',$this->crudMessage('update','product'));
        return redirect()->route('products.index');   
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function edit($id)
    {
        $product = $this->product->findData($id);
        return view('Admin.Product.edit',compact('product'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
	public function show($id)
    {   
        $product = $this->product->findData($id);
        return view('Admin.Product.view',compact('product')); 
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function destroy($id)
    {   
        $this->product->destroyData($id);
        notificationMsg('success',$this->crudMessage('delete','product'));
        return redirect()->route('products.index');
    }
}

resources/views/Admin/Product/create.blade.php
@extends('adminTheme.default')

@section('title')
Create Product
@endsection

@section('content')
<section class="content-header">
  <h1>
    Create Product
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('products.index') }}">Product</a></li>
    <li class="active">Create New Product</li>
  </ol>
</section>
<section class="content">
<a href="{{ route('products.index') }}" class="btn btn-primary btn-flat pull-right" data-toggle="tooltip" title="Back !"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><br><br>
<div class="box box-primary">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="fa fa-briefcase" aria-hidden="true"></i>
   
        <h3 class="box-title">Product</h3>
    </div>

    @if($errors->count() > 0)
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                @foreach($errors->all() as $er )
                    <ul>
                        <li>{{ $er }}</li>
                    </ul> 
                @endforeach
        </div>
    @endif

    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="modal-body">
                    {!! Form::open(array('route'=>'products.store','method'=>'POST','files'=>'true','enctype'=>'multipart/form-data')) !!}
                    <div class="row">
                        <div class="col-lg-6">
                           <div class="form-group">
                                <label>Name:</label>
                                {!! Form::text('name',null, ['class'=>'form-control']) !!}
                            </div> 
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Image:</label>
                                {!! Form::file('image',['class'=>'form-control']) !!}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Descrption:</label>
                        {!! Form::textarea('description',null, ['class'=>'form-control']) !!}
                    </div>
                    <div class="box-footer clearfix no-border">
                        <a href="{{ route('products.index') }}" class="btn btn-danger btn-flat pull-right" style="margin-left: 10px;" data-toggle="tooltip" title="Cancel !"><i class="fa fa-times" aria-hidden="true"></i></a>
                        
                        <button type="submit" class="btn btn-success pull-right btn-flat" data-toggle="tooltip" title="Submit !"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/Admin/Product/edit.blade.php
@extends('adminTheme.default')

@section('title')
Edit Product
@endsection

@section('content')
<section class="content-header">
  <h1>
    Create Product
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li><a href="{{ route('products.index') }}">Product</a></li>
    <li class="active">Edit</li>
  </ol>
</section>
<section class="content">
<a href="{{ route('products.index') }}" class="btn btn-primary btn-flat pull-right" data-toggle="tooltip" title="Back !"><i class="fa fa-arrow-left" aria-hidden="true"></i></a><br><br>
<div class="box box-primary">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">Product</h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="modal-body">
                    {!! Form::model($product, ['method'=>'PUT', 'route'=>['products.update',$product->id],'files'=>'true','enctype'=>'multipart/form-data']) !!}
                    <div class="row">
                        <div class="col-lg-6">
                            {!! Form::hidden('image_old', $product->image) !!}
                           <div class="form-group">
                                <label>Name:</label>
                                {!! Form::text('name',null, ['class'=>'form-control']) !!}
                                @if($errors->has('name'))
                                <div><span style="color:red;">{{ $errors->first('name')}}</span></div>
                                @endif
                            </div> 
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label>Image:</label>
                                {!! Form::file('image',['class'=>'form-control']) !!}
                                <img src="/upload/product/{{ $product->image }}" style="width:50px;height:50px;"></td>
                                @if($errors->has('image'))
                                <div><span style="color:red;">{{ $errors->first('image')}}</span></div>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label>Descrption:</label>
                        {!! Form::textarea('description',null, ['class'=>'form-control']) !!}
                        @if($errors->has('description'))
                        <div><span style="color:red;">{{ $errors->first('description')}}</span></div>
                        @endif
                    </div>
                    <div class="box-footer clearfix no-border">
                        <a href="{{ route('products.index') }}" class="btn btn-danger btn-flat pull-right" style="margin-left: 10px;" data-toggle="tooltip" title="Cancel !"><i class="fa fa-times" aria-hidden="true"></i></a>
                        <button type="submit" class="btn btn-success pull-right btn-flat" data-toggle="tooltip" title="Submit !"><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection

resources/views/Admin/Product/index.blade.php
@extends('adminTheme.default')

@section('title')
Manage Product
@endsection

@section('content')
<section class="content-header">
  <h1>
    <i class="fa fa-briefcase" aria-hidden="true"></i>
 Manage Product
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">Product</li>
  </ol>
</section>
<section class="content">
<div class="row">
    <div class="col-lg-12">
        <div class="pull-left">
            <h1 class="page-header">
            </h1>
        </div>
        <div class="pull-right">
        	<a href="{{ route('products.create') }}"><button class="btn btn-success btn-flat" data-toggle="tooltip" title="Create New Product !"><i aria-hidden="true" class="fa fa-plus"></i></button></a>

            <button class="btn btn-primary search-modules test btn-flat" data-toggle="tooltip" title="Search !"><i class="fa fa-search"></i>&nbsp;</button>
        </div>
    </div>
</div><br>
@include('Admin.Product.search')
<div class="box box-info">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <h3 class="box-title">Product list</h3>
    </div>
    <div class="box-body">
        <table class="table table-bordered">
    <thead>
        <tr>
            <th width="50px">No</th>
            <th>Image</th>
            <th>Name</th>
            <th>Description</th>
            <th width="220px">Action</th>
        </tr>
    </thead>
    <tbody>
    @if(!empty($product) && $product->count())
        @foreach($product as $key => $value)
        <tr>
            <td>{{ ++$key }}</td>
            <td><img src="/upload/product/{{ $value->image }}" style="width:100px;height:50px;"></td>
            <td>{{ $value->name }}</td>
            <td>{{ $value->description }}</td>
            <td>
                <a href="{{ route('products.edit',$value->id) }}" class="btn btn-info btn-sm btn-flat" data-toggle="tooltip" title="Edit !"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>

                <a href="{{ route('products.show',$value->id) }}" class="btn btn-success btn-sm btn-flat" data-toggle="tooltip" title="view !"><i class="fa fa-eye" aria-hidden="true"></i></a>

                <button class="btn btn-danger btn-sm btn-flat remove-crud" data-id="{{ $value->id }}" data-toggle="tooltip" data-placement="top" title="Delete" data-action="{{ route('products.destroy',$value->id) }}"><i class="fa fa-trash" aria-hidden="true"></i></button><br><br>

                <a href="{{ route('productsImages.index',$value->id) }}" class="btn btn-success btn-sm btn-flat" data-toggle="tooltip" title="Manage images !">Manage Images</a>
            </td>
        </tr>
        @endforeach
    @else
        <td colspan="6" class="text-center">There are no image.</td>
    @endif
    </tbody>
</table>
</div>
</section>
<div class="text-center">
    @if(!empty($product) && $product->count())
    {!! $product->appends(Input::all())->render() !!}
    @endif
</div>
@endsection
@section('script')
<script type="text/javascript">
    jQuery(".search-modules").click(function(e) {
        
        e.preventDefault();
        jQuery(".filter-panel").toggle("slow");

    });
</script>
@endsection

resources/views/Admin/Product/search.blade.php
<div class="box box-success filter-panel {{Input::get("filter",false)?'filter-in':'filter-out'}}">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <h3 class="box-title">Searching</h3>
    </div>
    <div class="box-body">
        {!! Form::open(array('method'=>'get','class'=>'form-filter form-inline')) !!}
        <ul class="search">
            <li>
                <div class='form-group'>
                    {!! Form::label('filter[name][value]', 'Name',array('class'=>'control-label')) !!}
                    {!! Form::text('filter[name][value]',Input::get("filter.name.value"),array('class'=>'form-control','placeholder'=>'Enter Name')) !!}{!! Form::hidden('filter[name][type]','7') !!}
                </div>
            </li>
            <li>
                <div class='form-group'>
                    {!! Form::label('filter[description][value]', 'Description',array('class'=>'control-label')) !!}
                    {!! Form::text('filter[description][value]',Input::get("filter.description.value"),array('class'=>'form-control','placeholder'=>'Enter Description')) !!}{!! Form::hidden('filter[description][type]','7') !!}
                </div>
            </li>
            <li>
                <div class='form-group'>
                    <br/>
                    <button class="btn btn-success btn-flat"><i class="fa fa-share-square-o" aria-hidden="true"></i> Submit</button>
                </div>
            </li>
        </ul>
        {!! Form::close() !!}
    </div>
</div>

resources/views/Admin/Product/view.blade.php
@extends('adminTheme.default')

@section('title')
View Product
@endsection

@section('content')
<section class="content-header">
  <h1>
    View Product
    <small>Control panel</small>
  </h1>
  <ol class="breadcrumb">
    <li><a href="{{ route('home') }}"><i class="fa fa-dashboard"></i>Home</a></li>
    <li><a href="{{ route('products.index') }}">Product</a></li>
    <li class="active">view</li>
  </ol>
</section>
<section class="content">
<a href="{{ route('products.index') }}" class="btn btn-primary btn-flat pull-right"><i class="fa fa-arrow-left" aria-hidden="true"></i> Back</a><br><br>
<div class="box box-primary">
    <div class="box-header ui-sortable-handle" style="cursor: move;">
        <i class="ion ion-clipboard"></i>
        <h3 class="box-title">View</h3>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-lg-12">
                <div class="modal-body">
                    <div class="row">
                        <div class="col-lg-12">
                            {!! Form::hidden('image_old', $product->image) !!}
                            <div class="form-group">
                                <label>Name:</label><br>
                                {{ $product->name }}
                            </div> 
                        </div>
                        
                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Description:</label><br>
                                {{ $product->description }}
                            </div>
                        </div>

                        <div class="col-lg-12">
                            <div class="form-group">
                                <label>Image:</label><br>
                                 <img src="/upload/product/{{ $product->image }}" style="width:150px;height: 150px;">
                            </div>
                        </div>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>
</section>
@endsection