routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/', array('as'=> 'front.home', 'uses' => 'FrontController@index'));

// contact route
Route::post('/contact', array('as'=> 'front.contact', 'uses' => 'FrontController@contact'));
Route::get('product/{slug}', array('as'=> 'front.product', 'uses' => 'FrontController@productIndex'));

Route::get('/home', 'HomeController@index')->middleware('auth')->name('home');

Route::group(['prefix' => 'admin'], function () {

	Route::resource('sliders', 'Admin\SliderController');
	Route::resource('products', 'Admin\ProductController');
	Route::resource('contacts', 'Admin\ContactController');
	Route::resource('settings', 'Admin\SettingController');

	Route::post('productImage/store', array('as'=> 'productsImages.store', 'uses' => 'Admin\ProductImgController@store'));
	Route::get('productImage/create/{id}', array('as'=> 'productsImages.create', 'uses' => 'Admin\ProductImgController@create'));
	Route::get('productImage/{id}', array('as'=> 'productsImages.index', 'uses' => 'Admin\ProductImgController@index'));
	Route::delete('productImage/delete/{id}', array('as'=> 'productsImages.destroy', 'uses' => 'Admin\ProductImgController@destroy'));

});

resources/views/adminTheme/alert.blade.php
@if ($errors->any())
<script type="text/javascript">
	toastr.error('Please check the form below for errors', 'Error Alert', {timeOut: 5000})
</script>
@endif

@if ($message = Session::get('success'))
<script type="text/javascript">
	toastr.success('<?php echo $message; ?>', 'Success Alert', {timeOut: 5000})
</script>
<?php Session::forget('success');?>
@endif

@if ($message = Session::get('error'))
<script type="text/javascript">
	toastr.error('<?php echo $message; ?>', 'Error Alert', {timeOut: 5000})
</script>
<?php Session::forget('error');?>
@endif

@if ($message = Session::get('warning'))
<script type="text/javascript">
	toastr.warning('<?php echo $message; ?>', 'Warning Alert', {timeOut: 5000})
</script>
<?php Session::forget('warning');?>
@endif

@if ($message = Session::get('info'))
<script type="text/javascript">
	toastr.info('<?php echo $message; ?>', 'Information Alert', {timeOut: 5000})
</script>
<?php Session::forget('info');?>
@endif

resources/views/adminTheme/default.blade.php
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <link rel="shortcut icon" href="{{ asset('adminTheme/dist/fevicon/favicon.png') }}" type="image/x-icon"/>
  <title>@yield('title','Royal-Poly-Plast')</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{{ asset('adminTheme/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('adminTheme/bower_components/font-awesome/css/font-awesome.min.css')}}">
  <!-- Ionicons -->
  <link rel="stylesheet" type="text/css" href="{{ asset('master.css') }}">
  <link rel="stylesheet" href="{{ asset('adminTheme/bower_components/Ionicons/css/ionicons.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('adminTheme/dist/css/AdminLTE.min.css')}}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{{ asset('adminTheme/dist/css/skins/_all-skins.min.css')}}">
  <!-- Morris chart -->
  <!-- jvectormap -->
  <!-- Date Picker -->
  <!-- Daterange picker -->
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{ asset('adminTheme/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')}}">

  <link href="{{ asset('adminTheme/css/bootstrap-toggle.min.css') }}" rel="stylesheet">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  <link href="{{ asset('adminTheme/css/toastr.min.css') }}" rel="stylesheet">
  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  <!-- jQuery 3 -->
  <script src="{{ asset('adminTheme/bower_components/jquery/dist/jquery.min.js')}}"></script>
  <script src="{{ asset('adminTheme/js/toastr.min.js') }}"></script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  @include('adminTheme.header')
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    @include('adminTheme.sidebar')
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    @include('adminTheme.alert')
    @yield('content')
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    @include('adminTheme.footer')
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>
<!-- ./wrapper -->

<!-- jQuery UI 1.11.4 -->
<script src="{{ asset('adminTheme/bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('adminTheme/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- Morris.js charts -->
<!-- Sparkline -->
<script src="{{ asset('adminTheme/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script>
<!-- jvectormap -->
<script src="{{ asset('adminTheme/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{ asset('adminTheme/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- jQuery Knob Chart -->
<script src="{{ asset('adminTheme/bower_components/jquery-knob/dist/jquery.knob.min.js')}}"></script>
<!-- daterangepicker -->
<script src="{{ asset('adminTheme/bower_components/moment/min/moment.min.js')}}"></script>
<!-- datepicker -->
<!-- Bootstrap WYSIHTML5 -->
<script src="{{ asset('adminTheme/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{ asset('adminTheme/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<script src="{{ asset('adminTheme/js/bootbox.js')}}"></script>
<!-- FastClick -->
<script src="{{ asset('adminTheme/bower_components/fastclick/lib/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('adminTheme/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('adminTheme/dist/js/pages/dashboard.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('adminTheme/dist/js/demo.js')}}"></script>
<script src="{{ asset('adminTheme/js/bootstrap-toggle.min.js') }}"></script>
<script src="{{ asset('master.js')}}"></script>
<script src="{{ asset('/adminTheme/js/bootstrap-toggle.min.js') }}"></script>

    @yield('script')
    
</body>
</html> 

resources/views/adminTheme/footer.blade.php
<!-- <div class="pull-right hidden-xs">
    <b>Version</b> 2.4.0
</div>
<strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights reserved. -->

resources/views/adminTheme/header.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>R</b>PP</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg">Royal Poly Plast</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          
          <!-- Notifications: style can be found in dropdown.less -->
         
          <!-- Tasks: style can be found in dropdown.less -->
         
          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{{ asset('adminTheme/dist/img/user2-160x160.jpg')}}" class="user-image" alt="User Image">
              <span class="hidden-xs">{{ Auth::user()->name }}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{{ asset('adminTheme/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>
              <!-- Menu Body -->
              
              <!-- Menu Footer-->
              <li class="user-footer">
                  <div class="pull-right">
                    <a href="{{ route('logout') }}" class="btn btn-default btn-flat" onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">Sign out</a>
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                             {{ csrf_field() }}
                          </form>
                  </div>
                  <div>
                    <a href="{{ route('settings.index') }}" class="btn btn-default btn-flat">Settings</a>
                  </div>
                </li>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
        </ul>
      </div>
    </nav>
  </header>

resources/views/adminTheme/sidebar.blade.php
<section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{{ asset('adminTheme/dist/img/user2-160x160.jpg')}}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Hi, {{ Auth::user()->name }}</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <?php
        $currentPageURL = URL::current();
        $pageArray = explode('/', $currentPageURL);
        $pageActive = isset($pageArray[4]) ? $pageArray[4] : 'home';
        ?>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>

        <li class="{{ $pageActive == 'home' ? 'active' : ''  }}">
            <a href="{{ route('home') }}">
                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
            </a>
        </li>
       
        <li class="{{ $pageActive == 'sliders' ? 'active' : ''  }}">
            <a href="{{ route('sliders.index') }}">
                <i class="fa fa-sliders" aria-hidden="true"></i> <span>Slider</span>
            </a>
        </li>

        <li class="{{ $pageActive == 'products' ? 'active' : ''  }}">
            <a href="{{ route('products.index') }}">
                <i class="fa fa-briefcase" aria-hidden="true"></i>
 <span>Product</span>
            </a>
        </li>

         <li class="{{ $pageActive == 'contacts' ? 'active' : ''  }}">
            <a href="{{ route('contacts.index') }}">
                <i class="fa fa-phone" aria-hidden="true"></i> <span>Contact</span>
            </a>
        </li>
        
      </ul>
    </section>